Assignment-1
Q1: Questions on Basic NumPy Array
(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [1]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [2]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Method 1
flatten1 = array1.flatten()

# Method 2
flatten2 = array1.ravel()

print(flatten1)
print(flatten2)


[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

comparison = np.array_equal(arr1, arr2)
print("Arrays are equal:", comparison)


Arrays are equal: True


(d) Find the most frequent value and their indice(s) in the following arrays:
i.
x = np.array([1,2,3,4,5,1,2,1,1,1])
ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
# i.
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_freq_val = np.bincount(x).argmax()
indices = np.where(x == most_freq_val)
print("Most frequent in x:", most_freq_val, "Indices:", indices)

# ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_val_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_val_y)
print("Most frequent in y:", most_freq_val_y, "Indices:", indices_y)


Most frequent in x: 1 Indices: (array([0, 5, 7, 8, 9]),)
Most frequent in y: 1 Indices: (array([0, 1, 2]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i.
Sum of all elements
ii.
iii.
Sum of all elements row-wise  
Sum of all elements column-wise

In [5]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = np.sum(gfg)
row_sum = np.sum(gfg, axis=1)
col_sum = np.sum(gfg, axis=0)

print("Total:", total_sum)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)


Total: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i.
Sum of diagonal elements
ii.
iii.
iv.
v.
Eigen values of matrix
Eigen vectors of matrix
Inverse of matrix
Determinant of matrix

In [6]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i.
diag_sum = np.trace(n_array)

# ii–v.
eig_vals, eig_vecs = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
det = np.linalg.det(n_array)

print("Diagonal Sum:", diag_sum)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse:\n", inverse)
print("Determinant:", det)


Diagonal Sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i.
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii.
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [9]:
import numpy as np

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product2 = np.dot(p2, q2)
print("Matrix Product:\n", product2)

# Flatten to 1D arrays for covariance
p2_flat = p2.flatten()
q2_flat = q2.flatten()

# Now compute covariance
cov2 = np.cov(p2_flat, q2_flat)
print("Covariance:\n", cov2)


Matrix Product:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [10]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner:\n", np.inner(x, y))
print("Outer:\n", np.outer(x.flatten(), y.flatten()))

# Cartesian Product
a = x.flatten()
b = y.flatten()
cart = np.array(np.meshgrid(a, b)).T.reshape(-1, 2)
print("Cartesian:\n", cart)


Inner:
 [[17 52]
 [13 62]]
Outer:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics
(a)
For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i.
ii.
iii.
Find element-wise absolute value
Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
Mean, Median and Standard Deviation of flattened array, of each column, and
each row
For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [11]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Absolute:\n", np.abs(array))

flat = array.flatten()
print("25,50,75% (flat):", np.percentile(flat, [25, 50, 75]))
print("Mean(flat):", np.mean(flat))
print("Median(flat):", np.median(flat))
print("Std(flat):", np.std(flat))


Absolute:
 [[1 2 3]
 [4 5 6]]
25,50,75% (flat): [-3.5 -0.5  2.5]
Mean(flat): -0.5
Median(flat): -0.5
Std(flat): 3.8622100754188224


For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [12]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Round:", np.round(a))


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i.
Sorted array
ii.
iii.
iv.
Indices of sorted array
4 smallest elements
5 largest elements

In [13]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(arr))
print("Sorted Index:", np.argsort(arr))
print("4 Smallest:", np.sort(arr)[:4])
print("5 Largest:", np.sort(arr)[-5:])


Sorted: [ 10  16  16  52  54  62 453]
Sorted Index: [0 3 4 1 5 2 6]
4 Smallest: [10 16 16 52]
5 Largest: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i.
Integer elements only
ii.
Float elements only

In [14]:
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print("Integers:", arr[arr == arr.astype(int)])
print("Floats:", arr[arr != arr.astype(int)])


Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]
